apiVersion: apps/v1
kind: Deployment
metadata:
  name: rimal-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rimal-server-1
  template:
    metadata:
      labels:
        app: rimal-server-1
    spec:
      containers:
      - name: rimal
        image: fouxh/rimal-server:latest
        ports:
        - containerPort: 7777
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: rimal-server-service-1
spec:
  selector:
    app: rimal-server-1
  ports:
  - protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 30777
  type: NodePort
