# نسخة 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rimal-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rimal-server-1
  template:
    metadata:
      labels:
        app: rimal-server-1
    spec:
      containers:
      - name: rimal
        image: fouxh/rimal-server:latest
        ports:
        - containerPort: 7777
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: rimal-server-service-1
spec:
  selector:
    app: rimal-server-1
  ports:
  - protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 30777
  type: NodePort
---
# نسخة 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rimal-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rimal-server-2
  template:
    metadata:
      labels:
        app: rimal-server-2
    spec:
      containers:
      - name: rimal
        image: fouxh/rimal-server:latest
        ports:
        - containerPort: 7777
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: rimal-server-service-2
spec:
  selector:
    app: rimal-server-2
  ports:
  - protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 31777
  type: NodePort
---
# نسخة 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rimal-server-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rimal-server-3
  template:
    metadata:
      labels:
        app: rimal-server-3
    spec:
      containers:
      - name: rimal
        image: fouxh/rimal-server:latest
        ports:
        - containerPort: 7777
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: rimal-server-service-3
spec:
  selector:
    app: rimal-server-3
  ports:
  - protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 32777
  type: NodePort
